### ISSUE TITLE
Incompatibility to current doctrine/dbal 2.13.*

### ISSUE THREAD

**Issue by alexander-schranz** [crate/crate-dbal#112]
It seems like that the crate connection does not implement the dbal `Connection` interface and so currently failing. For dbal 2.13.* (2.12.* works). See comment by @mdumoulin here https://github.com/doctrine/dbal/issues/4619#issuecomment-827900550.

EDIT: Seems like correct interface is used  over the [ServerInfoAwareInterface](https://github.com/crate/crate-dbal/blob/751f3b78f949c97eda15adc0254308e9d7944eed/src/Crate/DBAL/Driver/PDOCrate/PDOConnection.php#L28) but the false statement class is set for PDO.

**Comment by amotl** [comment]
Hi Alexander,

thanks for your report. We will work on the codebase on behalf of #105 and will see what we can do about adding support for Doctrine 2.13.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Ah that was quick. Thanks for #113 already!
