### ISSUE TITLE
BOOLEAN support for Crate-DBAL

### ISSUE THREAD

**Issue by kadryjanek** [crate/crate-dbal#19]
Creating <code>QueryBuilder</code> and executing sample query with:

<pre>
        $conn = DriverManager::getConnection(array(/*..*/));
        $qb = $conn->createQueryBuilder();
        $qb
            ->select('id', 'created_at')
            ->from('tweets', 't')
            ->where('t.retweeted = :retweeted')
            ->setParameter('retweeted', true)
            ->execute();
</pre>

throws an <code>Exception</code>:

<pre>
DBALException: An exception occurred while executing 'SELECT id, created_at FROM tweets t WHERE t.retweeted = ?' with params [true]:

SQLActionException[Can't convert "1" to boolean] 
</pre>

**Comment by chaudum** [comment]
hi @kadryjanek 
this issue was completely overlooked. we're very sorry for that. I'm going to look at the issue now and let you know when it is fixed.

**Comment by chaudum** [comment]
@kadryjanek 

Crate has stricter types than for example MySQL, that means you have to provide an explicit type for `setParameter()` if you have a different type than `PDO::PARAM_STRING` (which is default type).

```php
$conn = DriverManager::getConnection(array(/*..*/));
$qb = $conn->createQueryBuilder();
$qb->select('id', 'created_at')
   ->from('tweets', 't')
   ->where('t.retweeted = :retweeted')
   ->setParameter('retweeted', true, PDO::PARAM_BOOL)
   ->execute();
```

**Comment by kadryjanek** [comment]
Ok, this works for me now.
Thx
