### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by mountain-code** [crate/crate-dbal#25]
Hi ...

I'm currently playing with crate and symfony 2.8 on php 7.0.0-1~dotdeb+8.1.

I would love to install crate-dbal via composer in this environment. Do you have any information if php 7 will be supported in next version?

Thanks

**Comment by joemoe** [comment]
Hi @mountain-code, at the moment we have no timetable on when we will support PHP 7, but we are constantly working on our integrations. We'll tell you when we planned it.

**Comment by joemoe** [comment]
hi @mountain-code, we now tested it for php7 and made some minor fixes. https://crate.io/a/php7-support/
