### ISSUE TITLE
UNIQUE handling

### ISSUE THREAD

**Issue by cweiske** [crate/crate-dbal#31]
The current DBAL code silently discards `UNIQUE` commands on columns. This has bitten me in production now :/

https://github.com/crate/crate-dbal/blob/master/src/Crate/DBAL/Platforms/CratePlatform.php#L699

Please throw an exception telling people to use a primary key instead as described on https://crate.io/docs/reference/sql/ddl.html#primary-key

**Comment by chaudum** [comment]
@cweiske thanks for reporting! we'll provide a fix for that.

**Comment by mikethebeer** [comment]
@cweiske fixed with https://github.com/crate/crate-dbal/commit/cdcdd79625d398f0118c948c8e91ac3a9e488447 and released in crate-dbal v0.3.1
