### ISSUE TITLE
Not compatible with 2.3.5

### ISSUE THREAD

**Issue by l7s** [crate/crate-dbal#47]
Hi,

Latest version 0.3.1 of DBAL doesn't seem to be compatible with latest Crate.io 2.3.5. The reason being:

[CrateSchemaManager::listTableColumns](https://github.com/crate/crate-dbal/blob/d08dfcd19fbab3c7f143f534dc3c881196fe2b0d/src/Crate/DBAL/Schema/CrateSchemaManager.php#L55) is broken as getListTableConstraintsSQL returns empty string because [this line](https://github.com/crate/crate-dbal/blob/master/src/Crate/DBAL/Platforms/Crate057Platform.php#L70) should read:

`"WHERE table_name = '$t[1]' AND table_schema = '$t[0]' AND constraint_type = 'PRIMARY KEY'";`

note: `PRIMARY_KEY` -> `PRIMARY KEY`, however even if we fix that, result of the above query differs between 2.0.4 (where DBAL works OK) and 2.3.5.

v. 2.0.4:

`{"cols":["constraint_name","constraint_type"],"col_types":[[100,4],4],"rows":[[["id"],"PRIMARY_KEY"]],"rowcount":1,"duration":0.911611}
`
note: `constraint_name` returns **array** of PK column names

v. 2.3.5:

`{"cols":["constraint_name","constraint_type"],"col_types":[4,4],"rows":[["cdr_pk","PRIMARY KEY"]],"rowcount":1,"duration":0.915925}`

note: `constraint_name` returns **string** "table_name_pk" ?

Regards,
Chris

**Comment by joemoe** [comment]
hi @l7s,

we are currently overhauling the `crate-pdo`. there will be a new release this week.
will keep you up to date.

thanks,
joe

**Comment by Taliik** [comment]
hi @l7s

We just released `crate-pdo 1.0.0`, might want to give it a try again.
You can find the changes here: https://github.com/crate/crate-pdo/blob/master/CHANGES.rst

Regards,
Fabian
