### ISSUE TITLE
Latest DBAL v. 0.3.1 not compatible with Crate.io v. 2.3

### ISSUE THREAD

**Issue by l7s** [crate/crate-dbal#50]
Hi,

Latest DBAL v. 0.3.1 depends on PDO 0.6. see: 

https://github.com/crate/crate-dbal/blob/54ac194c999b70708d042f95bfd5e3db2b69aa05/composer.json#L12

therefore is NOT compatible with Crate.io 2.3. Would you be able to make new DBAL release that depends on PDO 1.0.0 to make it work with Crate.io 2.3?

Regards,
Chris

**Comment by mikethebeer** [comment]
@l7s apologies, we totally missed this issue. Crate-dbal has been released quite a view months ago in version 1.1.0 which should be compatible with CrateDB >= 2.3.
