### ISSUE TITLE
Flush functionality

### ISSUE THREAD

**Issue by RomanGorbatko** [crate/crate-dbal#63]
Hi guys,

I tried to create some row:
```$viewsTest = new ViewsTest();
$viewsTest->setPage('1');
$viewsTest->setPrevPage('2');

$this->getEntityManager()->persist($viewsTest);
$this->getEntityManager()->flush();
```

and I see this exception:
`Crate\PDO\Exception\UnsupportedException : Unsupported functionality`

Looks strange and it was not sufficiently informative.

I check `WriteTest.php` https://github.com/crate/crate-dbal/blob/master/test/Crate/Test/DBAL/Functional/WriteTest.php and I see what they write insert query like a PDO style. But I don't want to use PDO style, I want to use ORM style :slightly_smiling_face:

How I can make INSERT query through DBAL?

**Comment by seut** [comment]
@RomanGorbatko ORM style API's are implemented by the Doctrine ORM project while DBAL provides only a query abstraction level on top of PDO. This is why our DBAL project does not include ORM style tests as this is out-of-scope of any DBAL implementation.
After playing around with Doctrine ORM using the crate-dbal driver, I could not reproduce your issue.
Can you please provide more information like the full `$viewsTest` model definition and the `crate`, `crate-dbal`, `doctrine-dbal` and `doctrine-orm` versions you're using?

**Comment by RomanGorbatko** [comment]
@seut 

thanks for the reply!
my issue is resolved now. 

In my case, I used `$dtCreate->getTimestamp()` for `timestamp` column type. 
I have studied the source code of `TimestampType` and just replace `getTimestamp()` to `new DateTime()` for `DateTime` type casting.

Please just close my issue.

**Comment by seut** [comment]
@RomanGorbatko Great, good to hear, will close then.
