### ISSUE TITLE
DBAL 2.10

### ISSUE THREAD

**Issue by JulianMar** [crate/crate-dbal#80]
Hi. 

I just wanted to ask why the DBAL Version is locked to 2.9?
Due to the nature of `^` in semver the [laravel-crate.io](https://github.com/RatkoR/laravel-crate.io/blob/master/composer.json) package requires always 2.0 and adds dbal at version ^2.10.

Can this maybe be fixed? If I know the issue, I can even create a PR

Thanks for the answer

**Comment by seut** [comment]
@JulianMar 
We just did not test it with DBAL 2.10 yet. 
Would be really cool if you could contribute that!
Thank you for pointing out.
