### ISSUE TITLE
upgrade docs build system

### ISSUE THREAD

**Issue by norosa** [crate/crate-dbal#87]
this repo uses the old Crate docs build system. we should update it to use the new build system (https://github.com/crate/docs)

for instructions, see here: https://github.com/crate/crate-howtos/issues/163

**Comment by infoverload** [comment]
I am interested in this

**Comment by mechanomi** [comment]
@infoverload go for it. however, this work is currently blocked on https://github.com/crate/tech-writing-domain/issues/97 -- happy to work on that with you though and figure out a solution

**Comment by amotl** [comment]
Hi there,

I've identified those tasks:

- [ ] Don't use buildout, just use a `Makefile`
- [ ] Bump dependency versions of Sphinx, etc.
- [ ] Add documentation build to CI

With kind regards,
Andreas.

**Comment by mechanomi** [comment]
@amotl did you check out https://github.com/crate/crate-howtos/issues/163?

**Comment by amotl** [comment]
Thanks @mechanomi. I just added the docs-ng build system on behalf of #109.
